name: Test
on:
    push:
        branches:
            - 'develop'

jobs:
    build:
        name: Run detox
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node
              run: |
                  npm install -g react-native-cli
                  npm install -g detox-cli
                  npm install -g yarn
            - name: Install Detox
              run: |
                  brew tap wix/brew
                  brew install applesimutils
            - name: Install Yarn Dependencies
              run: yarn install
            # - name: Unit Tests
            #   run: yarn test
            - name: Install Pod Dependencies
              run: cd ./ios && pod install && cd ..
            - name: Detox Build
              run: yarn detox:build:release
            - name: Detox Test
              run: yarn detox:test:release
